"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import environ
from split_settings.tools import include

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load an .env file
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR.parent.joinpath(".env"))

SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

# By default, the django-environ splits a given string by a comma.
# the docs https://django-environ.readthedocs.io/en/latest/api.html#environ.Env.list
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1"])
INTERNAL_IPS = env.list("INTERNAL_IPS", default=["127.0.0.1"])
# static
# localization
LOCALE_PATHS = ["movies/locale"]

# WSGI
WSGI_APPLICATION = "config.wsgi.application"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.joinpath("static")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

include(
    "components/database.py",
    "components/application.py",
    "components/internalization.py",
    "components/password_validation.py",
    "components/logging.py",
    "components/authorization.py",
)
