"""create_social_accounts

Revision ID: 6a58b42ff86b
Revises: 23c76cecfd4d
Create Date: 2023-09-26 13:24:56.619499

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6a58b42ff86b"
down_revision = "23c76cecfd4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_accounts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("social_id", sa.String(length=255), nullable=False),
        sa.Column("provider_slug", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "email", "provider_slug", name="unique_together_email_provider_slug"
        ),
        sa.UniqueConstraint(
            "social_id", "provider_slug", name="unique_together_social_id_provider_slug"
        ),
        sa.UniqueConstraint(
            "user_id", "provider_slug", name="unique_together_user_id_provider_slug"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_accounts")
    # ### end Alembic commands ###
