"""users_on_delete_cascade

Revision ID: ec08fc185d67
Revises: 6a58b42ff86b
Create Date: 2023-09-29 22:56:13.717166

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec08fc185d67"
down_revision = "6a58b42ff86b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "social_accounts_user_id_fkey", "social_accounts", type_="foreignkey"
    )
    op.create_foreign_key(
        "social_accounts_user_id_fkey",
        "social_accounts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "user_login_history_user_id_fkey", "user_login_history", type_="foreignkey"
    )
    op.create_foreign_key(
        "user_login_history_user_id_fkey",
        "user_login_history",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "users_permissions_user_id_fkey", "users_permissions", type_="foreignkey"
    )
    op.create_foreign_key(
        "users_permissions_user_id_fkey",
        "users_permissions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "users_permissions_user_id_fkey", "users_permissions", type_="foreignkey"
    )
    op.create_foreign_key(
        "users_permissions_user_id_fkey",
        "users_permissions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "user_login_history_user_id_fkey", "user_login_history", type_="foreignkey"
    )
    op.create_foreign_key(
        "user_login_history_user_id_fkey",
        "user_login_history",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "social_accounts_user_id_fkey", "social_accounts", type_="foreignkey"
    )
    op.create_foreign_key(
        "social_accounts_user_id_fkey", "social_accounts", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
